### Create a new customer with address
POST http://localhost:8080/customers
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "Wasim Wasim",
  "addresses": [
    {
    "street": "123 Main Street",
    "city": "New York",
    "zipCode": "10001",
    "type": "HOME"
  },
    {
      "street": "Level 5, 456 Corporate Blvd",
      "city": "New York",
      "zipCode": "10002",
      "type": "WORK"
    }
  ]
}

###

### Get all customers
GET http://localhost:8080/customers
Authorization: Bearer {{auth_token}}

###

### Get customer by ID
GET http://localhost:8080/customers/3
Authorization: Bearer {{auth_token}}

###

