POST http://localhost:8080/orders
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "lineItems": [
    {
      "product": 1,
      "quantity": 1
    },
    {
      "product": 12,
      "quantity": 200
    }
  ]
}