### Create a new customer with address
POST http://localhost:8080/customers
Content-Type: application/json
Authorization: Bearer {{auth_token}}

{
  "name": "Jasim Wasim",
  "addresses": [
    {
    "street": "Dubai Marina Walk, Building 10",
    "city": "Dubai",
    "zipCode": "10001",
    "type": "HOME"
  },
    {
      "street": "Dubai Internet City, Building 5",
      "city": "Dubai",
      "zipCode": "10002",
      "type": "WORK"
    }
  ]
}

###

### Get all customers
GET http://localhost:8080/customers
Authorization: Bearer {{auth_token}}

###

### Get customer by ID
GET http://localhost:8080/customers/3
Authorization: Bearer {{auth_token}}

###

